all:
  children:
    # 마스터 노드 그룹
    master:
      hosts:
        master:
          ansible_host: 10.10.10.10  # 마스터 실제 IP

    # 워커 노드 그룹
    workers:
      hosts:
        worker01:
          ansible_host: 10.10.10.20
        worker02:
          ansible_host: 10.10.10.30


    # 전체 클러스터 그룹 (마스터 + 워커 포함)
    k8s_cluster:
      children:
        master:
        workers:
